packaging_format = 2

id = "tiki"
name = "Tiki"
description.en = "Wiki-based, content management system"
description.fr = "Système de gestion de contenu basé sur Wiki"

version = "27.0~ynh1"

maintainers = []

[upstream]
license = "LGPL-2.1-only"
website = "https://tiki.org/"
demo = "https://tiki.org/Try-Tiki"
admindoc = "https://doc.tiki.org"
code = "https://gitlab.com/tikiwiki/tiki/"

[integration]
yunohost = ">= 11.2.29"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "300M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/tiki"

    [install.release_cycle]
    ask.en = "Upgrade cycle"
    ask.fr = "Cycle de mises à jours"
    help.en = "Every 3 version is an LTS. LTS versions are supported for 5 years"
    help.fr = "Toutes les 3 versions sont des LTS qui sont maintenues pendant 5 ans"
    type = "select"
    choices.longterm = "Install latest Long Term Support version (recommended)"
    choices.regular = "Install latest version"
    default = "longterm"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://sourceforge.net/projects/tikiwiki/files/Tiki_27.x_Miaplacidus/27.0/tiki-27.0.tar.gz/download"
        sha256 = "bcc79422239e9b17846082bec4341326518e95a5c058307e61933c2382245dbb"
        format = "tar.gz"

        [resources.sources.lts]
        url = "https://sourceforge.net/projects/tikiwiki/files/Tiki_24.x_Wolf_359/24.6/tiki-24.6.tar.gz/download"
        sha256 = "1dc1a3f0236c79287b14bfe45eb789e8b0e5c89d2a9089bab496c61a2c73a9f0"
        format = "tar.gz"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "tesseract-ocr, imagemagick, mariadb-server"

    packages_from_raw_bash = """
            if [[ "$release_cycle" == "regular" ]]; then 
                echo "php8.1-bz2, php8.1-curl, php8.1-gd, php8.1-zip, php8.1-mysql, php8.1-xml, php8.1-mbstring, php8.1-intl"
            else
                echo "php7.4-bz2, php7.4-curl, php7.4-gd, php7.4-zip, php7.4-mysql, php7.4-xml, php7.4-mbstring, php7.4-intl"
            fi
        """

    [resources.database]
    type = "mysql"
