#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=15

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGINX web server..." --weight=1

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring PHP-FPM..." --weight=1

# Create a dedicated PHP-FPM config
ynh_add_fpm_config

#=================================================
# ADD INITIAL CONFIGURATION
#=================================================

# Define a function to execute commands with proper permissions
exec_as_app() {
  (cd "$install_dir" && ynh_exec_as "$app" \
      php${phpversion} --define apc.enable_cli=1 "$@")
}

ynh_script_progression --message="Create database configuration file..." --weight=1
exec_as_app console.php database:configure "$app" "$db_pwd" "$app"

ynh_script_progression --message="Create database contents..." --weight=1
exec_as_app console.php database:install

ynh_script_progression --message="Lock installer..." --weight=1
exec_as_app console.php installer:lock

ynh_script_progression --message="Create data index..." --weight=1
exec_as_app console.php index:rebuild

ynh_script_progression --message="Set on Long Term Support versions..." --weight=1
exec_as_app console.php preferences:set tiki_release_cycle longterm

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
