#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set --key=php_upload_max_filesize --value=256M

#REMOVEME? Everything about fpm_footprint is removed in helpers2.1... | fpm_footprint="low"
#REMOVEME? Everything about fpm_free_footprint is removed in helpers2.1... | fpm_free_footprint=0
#REMOVEME? Everything about fpm_usage is removed in helpers2.1... | fpm_usage="low"

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

#REMOVEME? Everything about fpm_footprint is removed in helpers2.1... | ynh_app_setting_set --key=fpm_footprint --value=$fpm_footprint
#REMOVEME? Everything about fpm_free_footprint is removed in helpers2.1... | ynh_app_setting_set --key=fpm_free_footprint --value=$fpm_free_footprint
#REMOVEME? Everything about fpm_usage is removed in helpers2.1... | ynh_app_setting_set --key=fpm_usage --value=$fpm_usage

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
source_id_to_use="main"
if [[ "$release_cycle" == "longterm" ]]
then
    source_id_to_use="lts"
fi

ynh_setup_source --dest_dir="$install_dir" --source_id="$source_id_to_use"

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data "$install_dir"
#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated PHP-FPM config
ynh_config_add_phpfpm

#=================================================
# ADD INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Configuring $app..."

# Define a function to execute commands with proper permissions
exec_as_app() {
  (cd "$install_dir" && ynh_exec_as_app \
      php${php_version} --define apc.enable_cli=1 "$@")
}

# Create database configuration file
ynh_hide_warnings exec_as_app console.php database:configure "$app" "$db_pwd" "$app"

# Create database contents
ynh_hide_warnings exec_as_app console.php database:install

# Set default database directory
cd "$install_dir"
sed -i -e "s#storage/fgal#$data_dir#" lib/prefs/fgal.php
# Lock installer
ynh_hide_warnings exec_as_app console.php installer:lock

# Create data index
ynh_hide_warnings exec_as_app console.php index:rebuild

# Set on Long Term Support versions
if [[ "$release_cycle" == "longterm" ]]
then
  ynh_hide_warnings exec_as_app console.php preferences:set tiki_release_cycle longterm
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
