#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set_default --key=php_upload_max_filesize --value=256M

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# If fpm_footprint doesn't exist, create it
if [ -z "${fpm_footprint:-}" ]; then
    fpm_footprint=low
# REMOVEME ? Everything about fpm_footprint is removed in helpers2.1... |     ynh_app_setting_set --key=fpm_footprint --value=$fpm_footprint
fi

# If fpm_free_footprint doesn't exist, create it
if [ -z "${fpm_free_footprint:-}" ]; then
    fpm_free_footprint=0
# REMOVEME ? Everything about fpm_free_footprint is removed in helpers2.1... |     ynh_app_setting_set --key=fpm_free_footprint --value=$fpm_free_footprint
fi

# If fpm_usage doesn't exist, create it
if [ -z "${fpm_usage:-}" ]; then
    fpm_usage=low
# REMOVEME ? Everything about fpm_usage is removed in helpers2.1... |     ynh_app_setting_set --key=fpm_usage --value=$fpm_usage
fi

# If release_cycle doesn't exist, create it
# FIXME: maybe replace with: ynh_app_setting_set_default --key=release_cycle --value=longterm
if [ -z "${release_cycle:-}" ]; then
    release_cycle=longterm
    ynh_app_setting_set --key=release_cycle --value=$release_cycle
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

if ynh_app_upstream_version_changed
then
	ynh_script_progression "Upgrading source files..."

	# Download, check integrity, uncompress and patch the source from app.src
    source_id_to_use="main"
    if [[ "$release_cycle" == "longterm" ]]
    then
        source_id_to_use="lts"
    fi

    ynh_setup_source --dest_dir="$install_dir" --source_id="$source_id_to_use"
fi

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

# Update database
(cd "$install_dir" && ynh_exec_as_app php${php_version} --define apc.enable_cli=1 console.php database:update)

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Upgrading NGINX web server configuration..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated PHP-FPM config
ynh_config_add_phpfpm

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
