#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set_default --key=php_upload_max_filesize --value=256M

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# If release_cycle doesn't exist, create it
if [ -z "${release_cycle:-}" ]; then
    release_cycle=longterm
    ynh_app_setting_set_default --key=release_cycle --value=$release_cycle
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
source_id_to_use="main"
if [[ "$release_cycle" == "longterm" ]]
then
    source_id_to_use="lts"
fi

ynh_setup_source --dest_dir="$install_dir" --source_id="$source_id_to_use"

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

# Update database
(cd "$install_dir" && ynh_exec_as_app php${php_version} --define apc.enable_cli=1 console.php database:update)

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_phpfpm

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
